# To launch the server : bundle exec jekyll serve

title: Nicolas Schneider - Associate Lead Programmer at Old Skull Games
url : "https://surue.github.io"

description: > # this means to ignore newlines until "show_excerpts:"
  I'm working at Old Skull Games as an Associate Lead Programer
show_excerpts: false # set to true to show excerpts on the homepage

# generate social links in footer

twitter_username: n_surue
github_username: surue
linkedin-username: nicolas-schneider-14135a170

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-relative-links
  - jekyll-feed
relative_links:
  enabled: true
  collections: true
  
collections:
    projects:
        output: true
