# Jekyll configuration
name : Surue's Blog Post
url : "https://surue.github.io"


# Build settings
theme: jekyll-theme-minimal

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
