# Jekyll configuration
name : Surue's Blog Post
url : "https://surue.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
